### ISSUE TITLE
[Feat] 커버이미지 생성 기능

### ISSUE THREAD

**Issue by loveysuby** [Princess-in-silvertown/toyou-server#26]
## 🚀 Highlights

- 포토카드 이미지 파일을 AI 모델 요청을 통해 생성하는 기능을 추가합니다.

## 📌 Tasks

- 포토카드는 사용자의 감정 파라미터를 기반으로 생성됩니다.

## 📝 Details

Write the details about the feature.
- [x] 감정 파라미터는 단어 형태의 keyword List로 전달되는 것으로 가정합니다.
  - [ ]이를 적절한 형태로 파싱하여 프롬프트에 embed하는 과정이 필요합니다.
- [x] spring-ai 혹은 Dall-e API 등으로 이미지 파일 혹은 이미지의 downloadbale URL을 서빙해야 합니다.
- [x] 컨텐츠가 제대로 서빙되는지 테스트해볼 필요가 있을 것 같아요.

## 📚 Remarks

- 회의에서 어떻게 일관된 방식으로 AI server와 통신할지 정해볼게요. (구현보다 prompt 가 중요하므로, spring-ai 필요성 낮다고 판단)
