### ISSUE TITLE
[Feat] Infra Credential submodule 구성 

### ISSUE THREAD

**Issue by loveysuby** [Princess-in-silvertown/toyou-server#53]
## 🚀 Highlights

Write the main purpose of the issue.
- Infra Credential submodule 구성 

## 📌 Tasks

List the features you plan to develop.

- github submodule 추가

## 📝 Details

Write the details about the feature.

- [x] #59
- [ ] - 공공데이터 프로세싱 모듈
- [x] - JWT 관련 credential
- [x] - Diffusion model 커넥션 관련 credential

## 📚 Remarks

-
