### ISSUE TITLE
[CI] AWS EC2 CI 배포 workflow 구성

### ISSUE THREAD

**Issue by loveysuby** [Princess-in-silvertown/toyou-server#72]
## 🚀 Highlights

Write the main purpose of the issue.
- 서비스 자동 배포를 위한 CI workflow를 구성합니다.

## 📌 Tasks

List the features you plan to develop.
- Github action 기반 EC2 CI workflow 작성

## 📝 Details

Write the details about the feature.

- [ ] 단일 배포용 AWS EC2 구성
- [ ] EC2 접근 권한 Role 설정 
- [ ] 해당 Role을 가진 사용자로 WAS 내 Github action CI workflow 구성
- [ ] nginx, swap memory 등 build 이전 설정 요구 task script 기술

## 📚 Remarks

- 데모 서비스 배포를 위한 단일 ec2를 사용합니다.
- Infra 프로비저닝 전략은 해당 환경 구성 이후 논의합니다. (Terraform + Ansible 도입 유용성을 판단합니다.)
