### ISSUE TITLE
[Feat] Toyou-Image-AI 모델 서버 연결

### ISSUE THREAD

**Issue by loveysuby** [Princess-in-silvertown/toyou-server#87]
## 🚀 Highlights

Write the main purpose of the issue.

-이미지 context 를 학습한 AI Model 서버와 통신을 구성합니다.

## 📌 Tasks

List the features you plan to develop.
- 내부 API Specification 규격 참조

## 📝 Details

Write the details about the feature.
- [x] 연결 테스트 및 응답 예외 구성 확인
  - [x] 2xx 응답 테스트
  - [x] 4xx, 5xx 응답 테스트

## 📚 Remarks

-
